### ISSUE TITLE
Add scoreboard

### ISSUE THREAD

**Issue by Bujnyy** [SAY10s/TheBindingOfIsaac-Genesis#1]
Players can't see their score. I'd love to see scoreboard in the game

**Comment by SAY10s** [comment]
The simples possible scoreboard was added in commit [430a4e4](https://github.com/SAY10s/TheBindingOfIsaac-Genesis/commit/430a4e487c99e06fafb9e66bf4ca4a8401cd2a7f). Styles will be added later.
